import Link from "next/link";
import Footer from "../components/footer";

// const AdminLayout = ({ children } : {children : React.ReactNode}) => {
  //  return (
  //      <html lang="en">
  //      <body
  //        className=""
  //      >
  //        <div className="bg-zinc-100 p-2">
            
  //          <nav className="flex justify-around items-center text-center">
  //              <Link href="./admin">Admin</Link>
  //              <Link href="./setting">Setting</Link>
  //              <Link href="./users">Users</Link>
  //              <Link href="./contact">Contact</Link>
  //              <Link href="./totalsell">TotalSell</Link>
  //          </nav>
  //        </div>
  //        <div>
  //          {children}
  //        </div>
  //        <div className="bg-blue-800 flex justify-around mx-auto items-center ">
            
  //          <Link href="./contact">Contact</Link>
  //          <Link href="./product_in_admin">Product</Link>
  //          <Link href="./services">Services</Link>
            
            
  //        </div> 
  //        <div>
  //          <Footer />
  //        </div>
  //      </body>
  //    </html>
  //  );
// }

// export default AdminLayout;

import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";



export const metadata: Metadata = {
  title: "Create Admin App for Admin Part",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=""
      >
        
        <div className="bg-zinc-100 p-2">
            
           <nav className="flex justify-around items-center text-center">
               <Link href="./admin">Admin</Link>
               <Link href="./setting">Setting</Link>
               <Link href="./users">Users</Link>
               <Link href="./contact">Contact</Link>
               <Link href="./totalsell">TotalSell</Link>
               <Link href="./lastmonth">LastMonth</Link>
           </nav>
         </div>
        
        <div>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
